employeeNumber = int(input())
workedHours = int(input())
salaryPerHour = float(input())
salary = (workedHours*salaryPerHour)
print("NUMBER = {0:.0f}".format(employeeNumber))
print("SALARY = U$ {0:.2f}".format(salary))